{
    "Target": {
        "EntitySet": "Books",
        "Service": "/MyApplicationMobile/Services/service1.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/MyApplicationMobile/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/MyApplicationMobile/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}